<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\ProjectsControl.Application\ProjectsControl.Application.csproj" />
      <ProjectReference Include="..\ProjectsControl.Entities\ProjectsControl.Entities.csproj" />
      <ProjectReference Include="..\ProjectsControl.Utils\ProjectsControl.Utils.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="9.0.0" />
    </ItemGroup>

</Project>
